name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/todo-sample-app
            git pull origin main
            docker build -t todo-sample-app ./server
            docker stop todo-sample-app || true
            docker rm todo-sample-app || true
            docker run -d \
              --name todo-sample-app \
              -p 3000:3000 \
              --network app-network \
              -e MONGO_URI=${{ secrets.MONGO_URI }} \
              -e MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} \
              todo-sample-app 